export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_CATEGORY = "GET_CATEGORY";

export const GET_SERVICES = "GET_SERVICES";

export const GET_SALON = "GET_SALON";
export const GET_SALONS = "GET_SALONS";
export const GET_SALON_SERVICES = "GET_SALON_SERVICES";
export const UPDATE_ACTIVE_FILTERS = "UPDATE_ACTIVE_FILTERS";
export const LOADING_SALONS = "LOADING_SALONS";

export const CREATED_RESERVATIONS_BY_SALON = "CREATED_RESERVATIONS_BY_SALON";

export const LOGIN = "LOGIN";

export const GET_CITIES = "GET_CITIES";
export const GET_SEARCH_TEXT = "GET_SEARCH_TEXT";

export const UPDATE_FILTERS = "UPDATE_FILTERS";
export const USER = "USER";
export const USER_LOGOUT = "USER_LOGOUT";
export const REGISTER_USER = "REGISTER_USER";
export const ADD_FAVORITE_SERVICE = "ADD_FAVORITE_SERVICE";
export const GET_FAVORITES = "GET_FAVORITES";
export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_FIELD = "UPDATE_USER_FIELD";
export const ADD_TO_BOOKINGS = "ADD_TO_BOOKINGS";
export const REMOVE_FROM_BOOKINGS = "REMOVE_FROM_BOOKINGS";
export const SHOW_FORM = "SHOW_FORM";
export const CLEAN_BOOKINGS = "CLEAN_BOOKINGS";
export const GET_BOOKINGS = "GET_BOOKINGS";
export const RECOVER_PASSWORD = "RECOVER_PASSWORD";
export const GET_RESERVES = "GET_RESERVES";
export const CANCEL_RESERVE = "CANCEL_RESERVE";
export const GET_DASHBOARD = "GET_DASHBOARD";
export const DEL_FAVORITE = "DEL_FAVORITE";
export const COUPON_VALIDATE = "COUPON_VALIDATE";
export const CLEAN_COUPON = "CLEAN_COUPON";
export const UPDATE_RESERVE = "UPDATE_RESERVE";
export const ADD_QUALIFICATION = "ADD_QUALIFICATION";
export const SHOW_FORM_REGISTER = "SHOW_FORM_REGISTER";
export const SET_REGISTER_ACTIVE_KEY = "SET_REGISTER_ACTIVE_KEY";
export const ADD_COUPON_TO_TOTAL = "ADD_COUPON_TO_TOTAL";
export const SET_ACTIVE_KEY = "SET_ACTIVE_KEY";
export const RESET_RESPONSE_RECOVER_PASSWORD =
  "RESET_RESPONSE_RECOVER_PASSWORD";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const RESET_UPDATED_USER = "RESET_UPDATED_USER";
export const UPDATED_USER = "UPDATED_USER";
export const GET_PROFESSIONALS = "GET_PROFESSIONALS";
export const GET_AVAIBLE_PROFESSIONALS = "GET_AVAIBLE_PROFESSIONALS";
export const GET_BLOCKED_PROFESSIONALS = "GET_BLOCKED_PROFESSIONALS";
export const GET_COUPONS = "GET_COUPONS";
export const DISABLED_RESERVATION_BTN = "DISABLED_RESERVATION_BTN";

export const GET_NEXT_PAGE_SERVICES = "GET_NEXT_PAGE_SERVICES";

export const GET_WEBSITE = "GET_WEBSITE";

export const GET_BRANDS = "GET_BRANDS";
export const GET_BRAND = "GET_BRAND";
